// TWIR version=1 hash=46c7979f2c305c8915a87392077cb243604ba061d206e4526c1a0282992c60a9 tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package main

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "rounded-lg", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusLg},
		}},
		style.Rule{Class: "border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderTopWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderRightWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderBottomWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderLeftWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "bg-card", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}},
		}},
		style.Rule{Class: "bg-card", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-950", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}},
		}},
		style.Rule{Class: "bg-linear-to-r", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGradient, Line: style.GradientLine{Kind: style.GradientLinear, Direction: style.ToRight}},
		}},
		style.Rule{Class: "from-indigo-600", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGradientFrom, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 79, G: 57, B: 246, A: 255}}},
		}},
		style.Rule{Class: "via-40%", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGradientViaPosition, Number: 0.4},
		}},
		style.Rule{Class: "to-pink-600", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGradientTo, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 230, B: 118, A: 255}}},
		}},
		style.Rule{Class: "p-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "p-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "text-zinc-100", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}},
		}},
		style.Rule{Class: "shadow-md", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShadow, Shadows: []style.Shadow{
				style.Shadow{X: 1, Y: 1, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 18}}, Tintable: true},
			}},
		}},
		style.Rule{Class: "inset-shadow-sm", Decls: []style.Declaration{
			style.Declaration{Property: style.PropInsetShadow, Shadows: []style.Shadow{
				style.Shadow{Y: 1, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 18}}, Inset: true, Tintable: true},
			}},
		}},
	})
}
