// TWIR version=1 hash=9d71ebc16842a346f325d92f26eb6c72fa1c5b460a9e49f0306bd461577fe3da tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package hello

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
	"github.com/twind-dev/twind/twi/theme"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "w-12", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 12}},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "gap-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "rounded-lg", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusLg},
		}},
		style.Rule{Class: "border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderTopWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderRightWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderBottomWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderLeftWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "border-none", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderStyle},
		}},
		style.Rule{Class: "bg-card", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}, Token: theme.Card, Mix: 100},
		}},
		style.Rule{Class: "bg-card", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}, Token: theme.Card, Mix: 100},
		}},
		style.Rule{Class: "bg-sky-800", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{G: 89, B: 138, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-800", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-950", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}},
		}},
		style.Rule{Class: "p-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "p-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "p-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "text-card-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.CardForeground, Mix: 100},
		}},
		style.Rule{Class: "text-card-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.CardForeground, Mix: 100},
		}},
		style.Rule{Class: "text-zinc-100", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}},
		}},
	})
}
