// TWIR version=1 hash=0cfd9506c7bae9efc9c4bf8d8ec790aac031e38547fe0a45be44f536d620e3c9 tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package hello

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "grid", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayGrid},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "rounded-lg", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusLg},
		}},
		style.Rule{Class: "border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderTopWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderRightWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderBottomWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderLeftWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "border-none", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderStyle},
		}},
		style.Rule{Class: "bg-zinc-950", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}},
		}},
		style.Rule{Class: "p-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "p-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "text-zinc-100", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}},
		}},
	})
}
