// TWIR version=1 hash=4182bae81767d7266b5585295ccdcc1781550f87b322ee4303bbb0a1f8f531c8 tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package chart

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
	"github.com/twind-dev/twind/twi/theme"
)

func styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "relative", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionRelative},
		}},
		style.Rule{Class: "z-50", Decls: []style.Declaration{
			style.Declaration{Property: style.PropZIndex, Number: 50},
		}},
		style.Rule{Class: "mt-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "block", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "grid", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayGrid},
		}},
		style.Rule{Class: "h-full", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Unit: style.Percent, Value: 100}},
		}},
		style.Rule{Class: "grow", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGrow, Number: 1},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "flex-row", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "justify-between", Decls: []style.Declaration{
			style.Declaration{Property: style.PropJustify, Justify: style.JustifyBetween},
		}},
		style.Rule{Class: "justify-center", Decls: []style.Declaration{
			style.Declaration{Property: style.PropJustify, Justify: style.JustifyCenter},
		}},
		style.Rule{Class: "gap-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "rounded", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusSm},
		}},
		style.Rule{Class: "rounded-md", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusMd},
		}},
		style.Rule{Class: "border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderTopWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderRightWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderBottomWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderLeftWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "bg-background", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}, Token: theme.Background, Mix: 100},
		}},
		style.Rule{Class: "bg-background", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.Background, Mix: 100},
		}},
		style.Rule{Class: "bg-border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "bg-border", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "bg-chart-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 255}}, Token: theme.Chart1, Mix: 100},
		}},
		style.Rule{Class: "bg-chart-1/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 77}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 77}}, Token: theme.Chart1, Mix: 30},
		}},
		style.Rule{Class: "bg-chart-1/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 153}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 153}}, Token: theme.Chart1, Mix: 60},
		}},
		style.Rule{Class: "bg-chart-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 255}}, Token: theme.Chart2, Mix: 100},
		}},
		style.Rule{Class: "bg-chart-2/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 77}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 77}}, Token: theme.Chart2, Mix: 30},
		}},
		style.Rule{Class: "bg-chart-2/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 153}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 153}}, Token: theme.Chart2, Mix: 60},
		}},
		style.Rule{Class: "bg-chart-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 255}}, Token: theme.Chart3, Mix: 100},
		}},
		style.Rule{Class: "bg-chart-3/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 77}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 77}}, Token: theme.Chart3, Mix: 30},
		}},
		style.Rule{Class: "bg-chart-3/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 153}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 153}}, Token: theme.Chart3, Mix: 60},
		}},
		style.Rule{Class: "bg-chart-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 255}}, Token: theme.Chart4, Mix: 100},
		}},
		style.Rule{Class: "bg-chart-4/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 77}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 77}}, Token: theme.Chart4, Mix: 30},
		}},
		style.Rule{Class: "bg-chart-4/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 153}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 153}}, Token: theme.Chart4, Mix: 60},
		}},
		style.Rule{Class: "bg-chart-5", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}, Token: theme.Chart5, Mix: 100},
		}},
		style.Rule{Class: "bg-chart-5/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 77}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 77}}, Token: theme.Chart5, Mix: 30},
		}},
		style.Rule{Class: "bg-chart-5/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 153}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 153}}, Token: theme.Chart5, Mix: 60},
		}},
		style.Rule{Class: "bg-muted", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}, Token: theme.Muted, Mix: 100},
		}},
		style.Rule{Class: "bg-muted", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}, Token: theme.Muted, Mix: 100},
		}},
		style.Rule{Class: "bg-muted/50", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 128}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 128}}, Token: theme.Muted, Mix: 50},
		}},
		style.Rule{Class: "bg-muted/50", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 128}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 128}}, Token: theme.Muted, Mix: 50},
		}},
		style.Rule{Class: "bg-popover", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}, Token: theme.Popover, Mix: 100},
		}},
		style.Rule{Class: "bg-popover", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}, Token: theme.Popover, Mix: 100},
		}},
		style.Rule{Class: "p-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "px-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "font-bold", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBold, Flag: true},
		}},
		style.Rule{Class: "font-medium", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBold},
		}},
		style.Rule{Class: "whitespace-pre", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWhiteSpace, WhiteSpace: style.WhiteSpacePre},
		}},
		style.Rule{Class: "text-border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "text-border", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "text-chart-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 255}}, Token: theme.Chart1, Mix: 100},
		}},
		style.Rule{Class: "text-chart-1/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 77}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 77}}, Token: theme.Chart1, Mix: 30},
		}},
		style.Rule{Class: "text-chart-1/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 153}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 212, G: 212, B: 216, A: 153}}, Token: theme.Chart1, Mix: 60},
		}},
		style.Rule{Class: "text-chart-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 255}}, Token: theme.Chart2, Mix: 100},
		}},
		style.Rule{Class: "text-chart-2/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 77}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 77}}, Token: theme.Chart2, Mix: 30},
		}},
		style.Rule{Class: "text-chart-2/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 153}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 153}}, Token: theme.Chart2, Mix: 60},
		}},
		style.Rule{Class: "text-chart-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 255}}, Token: theme.Chart3, Mix: 100},
		}},
		style.Rule{Class: "text-chart-3/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 77}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 77}}, Token: theme.Chart3, Mix: 30},
		}},
		style.Rule{Class: "text-chart-3/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 153}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 153}}, Token: theme.Chart3, Mix: 60},
		}},
		style.Rule{Class: "text-chart-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 255}}, Token: theme.Chart4, Mix: 100},
		}},
		style.Rule{Class: "text-chart-4/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 77}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 77}}, Token: theme.Chart4, Mix: 30},
		}},
		style.Rule{Class: "text-chart-4/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 153}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 153}}, Token: theme.Chart4, Mix: 60},
		}},
		style.Rule{Class: "text-chart-5", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}, Token: theme.Chart5, Mix: 100},
		}},
		style.Rule{Class: "text-chart-5/30", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 77}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 77}}, Token: theme.Chart5, Mix: 30},
		}},
		style.Rule{Class: "text-chart-5/60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 153}}},
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 153}}, Token: theme.Chart5, Mix: 60},
		}},
		style.Rule{Class: "text-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.Foreground, Mix: 100},
		}},
		style.Rule{Class: "text-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.Foreground, Mix: 100},
		}},
		style.Rule{Class: "text-muted", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}, Token: theme.Muted, Mix: 100},
		}},
		style.Rule{Class: "text-muted", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}, Token: theme.Muted, Mix: 100},
		}},
		style.Rule{Class: "text-muted-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 255}}, Token: theme.MutedForeground, Mix: 100},
		}},
		style.Rule{Class: "text-muted-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 159, G: 159, B: 169, A: 255}}, Token: theme.MutedForeground, Mix: 100},
		}},
		style.Rule{Class: "text-popover-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.PopoverForeground, Mix: 100},
		}},
		style.Rule{Class: "text-popover-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.PopoverForeground, Mix: 100},
		}},
		style.Rule{Class: "shadow-md", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShadow, Shadows: []style.Shadow{
				style.Shadow{Y: 4, Blur: 6, Spread: -1, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
				style.Shadow{Y: 2, Blur: 4, Spread: -2, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
			}},
		}},
		style.Rule{Class: "ring", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRingWidth, Number: 1},
		}},
	})
}
