package docsapp

import "slices"

type prop struct{ name, kind, about string }

func props() map[string][]prop {
	children := prop{"children", "...twi.NodeOption", "content, handlers and classes; a class merges over the defaults"}
	disabled := prop{"Disabled", "bool", "greys it out and takes it out of the Tab order"}
	open := []prop{
		{"Open", "bool", "whether it is showing"},
		{"OnOpenChange", "func(bool)", "called on every open and close"},
	}
	anchored := slices.Clip(append(open,
		prop{"Side", "ui.Side", "Bottom, Top, Right or Left of the trigger"},
		prop{"Align", "ui.Alignment", "Center, Start or End along that side"},
		prop{"Node(children...)", "twi.Node", "wraps the trigger and the content; a press outside closes it"},
		prop{"Trigger(v, s, children...)", "twi.Node", "a button that opens it"},
	))
	dialog := slices.Clip(append(open,
		prop{"Trigger(v, s, children...)", "twi.Node", "a button that opens it"},
		prop{"Content(children...)", "twi.Node", "the panel, over a dimmed page"},
		prop{"Header, Footer, Title, Description", "twi.Node", "the panel's parts"},
		prop{"Close(v, s, children...)", "twi.Node", "a button that closes it"},
	))
	return map[string][]prop{
		"Accordion": {
			{"Type", "ui.AccordionType", "Single keeps one section open, Multiple any number"},
			{"Collapsible", "bool", "with Single, lets the open section close again"},
			{"Value", "[]string", "the open sections"},
			{"OnChange", "func([]string)", "called when a section opens or closes"},
			{"Item(value, children...)", "twi.Node", "one section"},
			{"Trigger(value, children...)", "twi.Node", "the heading that toggles its section"},
			{"Content(value, children...)", "twi.Node", "shown while its section is open"},
		},
		"Alert": {
			{"v", "ui.Variant", "Default or Destructive"},
			{"AlertTitle, AlertDescription", "twi.Node", "the parts"},
			children,
		},
		"AlertDialog": append(dialog, prop{"ui.NewAlertDialog(rt)", "*ui.Dialog", "a dialog with no close button that a click outside does not close"}),
		"AspectRatio": {
			{"children", "...twi.NodeOption", "an aspect-* class sets the ratio; aspect-square by default"},
		},
		"Avatar": {
			{"s", "ui.Size", "SizeSM, SizeDefault or SizeLG"},
			{"AvatarFallback(children...)", "twi.Node", "the initials shown in the circle"},
		},
		"Badge": {
			{"v", "ui.Variant", "Default, Secondary, Destructive, Outline, Ghost or Link"},
			children,
		},
		"Breadcrumb": {
			{"BreadcrumbList, BreadcrumbItem", "twi.Node", "the row and one step in it"},
			{"BreadcrumbLink", "twi.Node", "a step you can open; give it twi.OnClick"},
			{"BreadcrumbPage", "twi.Node", "the current page"},
			{"BreadcrumbSeparator, BreadcrumbEllipsis", "twi.Node", "a chevron, or … for collapsed steps"},
		},
		"Button": {
			{"v", "ui.Variant", "Default, Secondary, Destructive, Outline, Ghost or Link"},
			{"s", "ui.Size", "SizeDefault, SizeXS, SizeSM, SizeLG or SizeIcon"},
			children,
		},
		"ButtonGroup": {
			{"o", "ui.Orientation", "Horizontal or Vertical"},
			{"ButtonGroupSeparator(o)", "twi.Node", "a line between two filled buttons; outline buttons join without one"},
			{"ButtonGroupText(children...)", "twi.Node", "text that sits in the group like a button"},
		},
		"Attachment": {
			{"u", "ui.Upload", "Done, Idle (a dashed border), Uploading, Processing or Failed (destructive)"},
			{"o", "ui.Orientation", "Horizontal, media beside the text, or Vertical, media above it"},
			{"AttachmentMedia(v, children...)", "twi.Node", "an Icon or an Image tile"},
			{"AttachmentContent, AttachmentTitle, AttachmentDescription", "twi.Node", "the text; title and description truncate"},
			{"AttachmentActions, AttachmentAction", "twi.Node", "small ghost buttons at the end, or the top right when vertical"},
			{"AttachmentTrigger(children...)", "twi.Node", "a focusable layer over the whole attachment; give it twi.OnClick"},
			{"AttachmentGroup(children...)", "twi.Node", "a row of attachments that scrolls sideways"},
		},
		"Bubble": {
			{"v", "ui.Variant", "Default, Secondary, Muted, Tinted, Outline, Ghost or Destructive"},
			{"a", "ui.Alignment", "Start or End; End also comes from an end-aligned Message"},
			{"BubbleContent(children...)", "twi.Node", "the coloured box; at most four fifths of the message wide, wraps"},
			{"BubbleReactions(side, a, children...)", "twi.Node", "a chip under (Bottom) or over (Top) a corner"},
			{"BubbleGroup(children...)", "twi.Node", "consecutive bubbles from one sender"},
		},
		"Calendar": {
			{"Month", "time.Time", "the month shown; follows Selected or Today when zero"},
			{"Selected", "time.Time", "the chosen day"},
			{"Today", "time.Time", "the day marked as today"},
			{"OnSelect", "func(time.Time)", "called when a day is chosen"},
			disabled,
		},
		"Card": {
			{"CardHeader, CardTitle, CardDescription", "twi.Node", "the top of the card"},
			{"CardAction", "twi.Node", "a control in the header's top right corner"},
			{"CardContent, CardFooter", "twi.Node", "the body and the bottom row"},
		},
		"Chart": {
			{"Kind", "chart.Kind", "Bar, Line, Area, Pie, Donut, Radial, Radar or Map"},
			{"Stacked", "bool", "stacks the series of a bar or area chart on each other"},
			{"Horizontal", "bool", "bars run left to right with their labels on the left"},
			{"Step", "bool", "line and area curves step halfway between points"},
			{"Labelled", "bool", "writes each bar's value at its end"},
			{"Dither", "bool", "draws every fill as an ordered dither of solid dots"},
			{"Brush", "bool", "adds an overview strip under an area or line chart; drag across it to zoom, click it to show everything"},
			{"From, To", "int", "the window of labels shown, To excluded; zero To means to the end"},
			{"Labels", "[]string", "one label per point; one label for a pie, donut or radial; country codes (ISO 3166 alpha-3) for a map"},
			{"Series", "[]chart.Series", "a Label, a Color from theme.Chart1 to theme.Chart5, an optional Negative colour for values below zero, and one value per label; a pie, donut or radial takes one series per slice or ring, a map one series"},
			{"Width, Height", "int", "the size in cells, axis and legend included"},
			{"Node(options...)", "twi.Node", "the chart, drawn as pixels where the terminal has graphics and as half blocks where it has none; the pointer over a point, slice or country shows its values"},
		},
		"Checkbox": {
			{"Checked", "bool", "whether it is ticked"},
			{"OnChange", "func(bool)", "called when it flips"},
			{"Invalid", "bool", "draws a destructive ring"},
			disabled,
		},
		"Collapsible": append(open,
			prop{"Node(children...)", "twi.Node", "the whole block"},
			prop{"Trigger(v, s, children...)", "twi.Node", "a button that flips it"},
			prop{"AsTrigger()", "twi.NodeOption", "makes any element flip it on a click"},
			prop{"Content(children...)", "twi.Node", "shown while it is open"},
		),
		"Combobox": {
			{"Value", "string", "the chosen item's value"},
			{"Placeholder, Empty", "string", "the field's hint, and the text when nothing matches"},
			{"ShowClear", "bool", "an x in place of the chevron while the field holds text"},
			{"OnChange", "func(string)", "called when an item is chosen"},
			{"Node(children...)", "twi.Node", "wraps the field and the list"},
			{"Input(options...)", "twi.Node", "the field that filters as you type"},
			{"Content(children...)", "twi.Node", "the list under the field"},
			{"Item(value, label, children...)", "twi.Node", "one choice"},
		},
		"Command": {
			{"Empty", "string", "shown when nothing matches"},
			{"OnSelect", "func(string)", "called with the chosen item's value"},
			{"Search(s)", "func(string)", "sets the search text"},
			{"Node(children...)", "twi.Node", "the box"},
			{"Input(placeholder)", "twi.Node", "the search field"},
			{"List(groups...)", "twi.Node", "ranks and shows the matching items"},
			{"Group(heading, items...), Separator()", "ui.CommandGroup", "a titled group, or a line between groups"},
			{"Item(value, children...)", "ui.CommandItem", "one item; the value is what the search matches"},
			{"CommandShortcut(children...)", "twi.Node", "keys shown on the right of an item"},
		},
		"CommandDialog": {
			{"Hotkey", "rune", "Ctrl and this key open and close it, k by default"},
			{"Open, OnOpenChange", "bool, func(bool)", "as on a dialog"},
			{"Trigger(v, s, children...)", "twi.Node", "a button that opens it"},
			{"Node(children...)", "twi.Node", "the dialog; put Input and List inside"},
		},
		"ContextMenu": {
			{"OnSelect", "func(string)", "called with the chosen item's text"},
			{"Node(children...)", "twi.Node", "wraps the area and the menu"},
			{"Trigger(children...)", "twi.Node", "the area; a right click or Shift+F10 opens the menu there"},
			{"Content(children...)", "twi.Node", "the menu; takes the same items as a dropdown menu"},
		},
		"Dialog": dialog,
		"Drawer": append(dialog, prop{"ui.NewDrawer(rt, side)", "*ui.Dialog", "a panel that slides in from one edge; from the bottom, drag its handle down to close it"}),
		"DropdownMenu": append(anchored[:4:4],
			prop{"OnSelect", "func(string)", "called with the chosen item's text"},
			prop{"Node, Trigger, Content", "twi.Node", "the wrapper, the button and the menu"},
			prop{"Item(text, children...)", "twi.Node", "one action"},
			prop{"CheckboxItem(text, *bool), RadioItem(text, *string)", "twi.Node", "items that flip a bool or pick a string"},
			prop{"Sub()", "*ui.DropdownMenuSub", "a submenu with its own Node, Trigger(text) and Content"},
			prop{"DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuShortcut", "twi.Node", "a heading, a line, and keys on the right"},
		),
		"Field": {
			{"o", "ui.Orientation", "Vertical puts the label above, Horizontal beside"},
			{"FieldSet, FieldLegend, FieldGroup", "twi.Node", "a titled set of fields"},
			{"FieldLabel, FieldDescription, FieldError", "twi.Node", "the label, a hint and an error"},
			{"FieldSeparator(children...)", "twi.Node", "a line, with optional text in the middle"},
		},
		"Form": {
			{"Input, Textarea, Checkbox, Select(key, control, rules...)", "func", "register a control; a rule returns the message to show, or an empty string"},
			{"OnSubmit", "func(ui.FormValues)", "called once when every rule passes, with Text and Checked keyed by name"},
			{"Item(key, children...)", "twi.Node", "a vertical field that adds the message under its children"},
			{"Label(key, children...)", "twi.Node", "a label that turns destructive while the field has a message"},
			{"Control(key, options...)", "twi.Node", "the registered control; Enter in an Input submits"},
			{"Submit()", "func()", "validates every field, focuses the first invalid one, or calls OnSubmit"},
			{"Reset()", "func()", "restores the registered values and clears every message"},
		},
		"HoverCard": append(anchored, prop{"Content(children...)", "twi.Node", "shown while the pointer or the focus is on the trigger"}),
		"Input": {
			{"Placeholder", "string", "shown while it is empty"},
			{"Value()", "string", "what it holds"},
			{"Insert(s)", "func(string)", "types text at the cursor"},
			{"Submit", "func(string)", "called by Enter with the trimmed text, which then clears and joins the Up history"},
			{"Invalid", "bool", "draws a destructive ring"},
			disabled,
			{"Node(options...)", "twi.Node", "the field"},
		},
		"InputGroup": {
			{"Group(addons...)", "twi.Node", "an Input or Textarea with addons inside its border"},
			{"InputGroupAddon(align, children...)", "ui.Addon", "InlineStart, InlineEnd, BlockStart or BlockEnd"},
			{"InputGroupText, InputGroupButton", "twi.Node", "text or a small button inside an addon"},
		},
		"InputOTP": {
			{"Length", "int", "how many slots, set by ui.NewInputOTP(rt, length)"},
			{"Value", "string", "the letters and digits entered"},
			{"OnChange", "func(string)", "called on every change"},
			{"Slot(i)", "twi.Node", "the box for one character"},
			{"InputOTPGroup, InputOTPSeparator", "twi.Node", "a run of slots and a dash between runs"},
		},
		"Carousel": {
			{"Orientation", "ui.Orientation", "Horizontal, Left and Right turn it, or Vertical, Up and Down"},
			{"Index", "int", "the slide shown"},
			{"OnChange", "func(int)", "called on every turn"},
			{"Node(children...)", "twi.Node", "the focusable region; it wraps at both ends"},
			{"Content(children...), Item(children...)", "twi.Node", "the viewport and one slide; the new slide slides in"},
			{"Previous(children...), Next(children...)", "twi.Node", "round buttons outside its sides"},
		},
		"Item": {
			{"v", "ui.Variant", "Default, Outline or Muted"},
			{"s", "ui.Size", "SizeDefault or SizeSM"},
			{"ItemMedia(v, children...)", "twi.Node", "an icon or image; v is Default, Icon or Image"},
			{"ItemContent, ItemTitle, ItemDescription, ItemActions", "twi.Node", "the parts of the row"},
			{"ItemGroup, ItemSeparator", "twi.Node", "a list of items and a line between them"},
		},
		"Direction": {
			{"dir", "text.Direction", "text.DirRTL or text.DirLTR; descendants inherit it until one sets its own"},
			children,
		},
		"Kbd": {
			{"Kbd(children...)", "twi.Node", "one key"},
			{"KbdGroup(children...)", "twi.Node", "keys pressed together"},
		},
		"Label": {children},
		"Marker": {
			{"v", "ui.Variant", "Default, Ruled (a line either side) or Bordered (a line under)"},
			{"MarkerIcon, MarkerContent", "twi.Node", "a leading glyph and the text"},
			children,
		},
		"Message": {
			{"a", "ui.Alignment", "Start, or End for the sender: the avatar moves right and the content aligns right"},
			{"MessageAvatar(children...)", "twi.Node", "at the bottom of the message; put a ui.Avatar in it"},
			{"MessageContent(children...)", "twi.Node", "the column of header, bubbles and footer"},
			{"MessageHeader, MessageFooter", "twi.Node", "muted lines above and below"},
			{"MessageGroup(children...)", "twi.Node", "a column of messages"},
		},
		"MessageScroller": {
			{"Node(children...)", "twi.Node", "the frame; give it a height"},
			{"Viewport(children...)", "twi.Node", "the focusable scrolling column; follows new content while at its end"},
			{"Item(children...)", "twi.Node", "one row, usually a Message"},
			{"Button(children...)", "twi.Node", "shown while scrolled up; jumps to the latest and follows again"},
		},
		"Menubar": {
			{"Menu()", "*ui.MenubarMenu", "adds a menu; it has Node, Trigger(children...) and Content like a dropdown menu"},
			{"Node(children...)", "twi.Node", "the bar"},
			{"OnSelect", "func(string)", "on each menu, called with the chosen item's text"},
		},
		"NativeSelect": {
			{"Options", "[]string", "the choices"},
			{"Value", "string", "the chosen one"},
			{"OnChange", "func(string)", "called when it changes"},
			disabled,
		},
		"NavigationMenu": {
			{"Value", "string", "the open item, empty when all are closed"},
			{"OnSelect", "func(string)", "called with the followed link's href"},
			{"Item(value)", "*ui.NavigationMenuItem", "adds an item with Node, Trigger, Content and Link(href, children...)"},
			{"Node, List", "twi.Node", "the wrapper and the row of triggers"},
		},
		"Pagination": {
			{"Pagination, PaginationContent, PaginationItem", "twi.Node", "the row and its slots"},
			{"PaginationLink(isActive, children...)", "twi.Node", "a page number; the active one is outlined"},
			{"PaginationPrevious, PaginationNext, PaginationEllipsis", "twi.Node", "the ends and a gap"},
		},
		"Popover": append(anchored, prop{"Content(children...)", "twi.Node", "the panel; Escape or a press outside closes it"}),
		"Progress": {
			{"value", "int", "from 0 to 100"},
			children,
		},
		"RadioGroup": {
			{"Value", "string", "the chosen item"},
			{"OnChange", "func(string)", "called when it changes"},
			{"Item(value, options...)", "twi.Node", "one choice with its label"},
			disabled,
		},
		"Resizable": {
			{"Orientation", "ui.Orientation", "Horizontal, panels side by side, or Vertical, stacked"},
			{"Sizes", "[]int", "each panel's percent of the group; even when left empty"},
			{"OnResize", "func([]int)", "called with the new sizes on every move"},
			{"Node(children...), Panel(children...)", "twi.Node", "the group and one panel"},
			{"Handle(withHandle, children...)", "twi.Node", "the line between two panels; drag it, or focus it and use the arrows, Home and End"},
		},
		"ScrollArea": {
			{"children", "...twi.NodeOption", "give it a height; the wheel, arrows and PageDown scroll it"},
		},
		"Select": append(anchored[:5:5],
			prop{"Value, Placeholder", "string", "the chosen value and the hint shown before a choice"},
			prop{"OnChange", "func(string)", "called when it changes"},
			prop{"Trigger(children...), Content(children...)", "twi.Node", "the field and the list"},
			prop{"Item(value, label, children...)", "twi.Node", "one choice"},
			prop{"SelectLabel, SelectSeparator", "twi.Node", "a group heading and a line"},
		),
		"Separator": {
			{"o", "ui.Orientation", "Horizontal or Vertical"},
			children,
		},
		"Sheet": append(dialog, prop{"ui.NewSheet(rt, side)", "*ui.Dialog", "a dialog that slides in from Top, Right, Bottom or Left"}),
		"Sidebar": {
			{"Open, OnOpenChange", "bool, func(bool)", "expanded or collapsed to icons"},
			{"Hotkey", "rune", "Ctrl and this key toggle it, b by default"},
			{"Provider(children...)", "twi.Node", "holds the sidebar and the inset side by side"},
			{"Node(children...), Trigger()", "twi.Node", "the sidebar and a button that toggles it"},
			{"SidebarHeader, SidebarContent, SidebarFooter", "twi.Node", "its top, scrolling middle and bottom"},
			{"SidebarGroup, SidebarGroupLabel, SidebarGroupContent", "twi.Node", "a titled group"},
			{"SidebarMenu, SidebarMenuItem, SidebarMenuButton(s, active, ...)", "twi.Node", "the entries"},
			{"SidebarMenuBadge, SidebarMenuSub...", "twi.Node", "a count and nested entries"},
			{"SidebarInset(children...)", "twi.Node", "the main area beside it"},
		},
		"Skeleton": {children},
		"Slider": {
			{"Value, Min, Max, Step", "int", "0 to 100 in steps of 1 by default"},
			{"OnChange", "func(int)", "called when it moves"},
			disabled,
		},
		"Spinner": {
			{"Node(options...)", "twi.Node", "turns while it is on screen and stops asking for frames when it is not"},
		},
		"Switch": {
			{"Checked", "bool", "on or off"},
			{"OnChange", "func(bool)", "called when it flips"},
			disabled,
		},
		"Table": {
			{"TableHeader, TableBody, TableFooter", "twi.Node", "the sections"},
			{"TableRow, TableHead, TableCell", "twi.Node", "a row and its cells; cells share the width"},
			{"TableCaption", "twi.Node", "a line under the table"},
		},
		"Tabs": {
			{"Value", "string", "the selected tab, the first trigger by default"},
			{"OnChange", "func(string)", "called when the selection changes"},
			{"Orientation", "ui.Orientation", "Horizontal or Vertical"},
			{"List(children...)", "twi.Node", "the row of triggers"},
			{"Trigger(value, children...)", "twi.Node", "selects its panel"},
			{"Content(value, children...)", "twi.Node", "shown while its value is selected"},
		},
		"Textarea": {
			{"Placeholder", "string", "shown while it is empty"},
			{"Value(), Insert(s)", "string", "what it holds, and typing at the cursor"},
			{"Submit", "func(string)", "called by Enter with the trimmed text, which then clears and joins the Up history; Shift+Enter breaks the line"},
			{"Invalid", "bool", "draws a destructive ring"},
			disabled,
		},
		"Toaster": {
			{"Duration", "time.Duration", "how long a toast stays"},
			{"Show, Success, Error", "func(title, description, ui.ToastAction)", "adds a toast"},
			{"Avoid(panels...)", "func(...*ui.Dialog)", "sheets and drawers the stack moves beside or above while open"},
			{"Node()", "twi.Node", "the stack in the corner; render it once"},
		},
		"Toggle": {
			{"Variant", "ui.Variant", "Default or Outline"},
			{"Size", "ui.Size", "SizeDefault, SizeSM or SizeLG"},
			{"Pressed", "bool", "on or off"},
			{"OnChange", "func(bool)", "called when it flips"},
		},
		"ToggleGroup": {
			{"Variant, Size", "ui.Variant, ui.Size", "as on a toggle"},
			{"Multiple", "bool", "lets more than one item be on"},
			{"Value", "[]string", "the items that are on"},
			{"OnChange", "func([]string)", "called on every change"},
			{"Item(value, options...)", "twi.Node", "one toggle"},
		},
		"Tooltip": append(anchored, prop{"Content(children...)", "twi.Node", "shown on hover or focus, above the trigger by default"}),
	}
}
