// TWIR version=1 hash=137ed417fee9b0ad8d19c1d311908be985f5f0b3bdff5c57d5af7340151613cf tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package sheet

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
	"github.com/twind-dev/twind/twi/theme"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "absolute", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionAbsolute},
		}},
		style.Rule{Class: "fixed", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionFixed},
		}},
		style.Rule{Class: "relative", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionRelative},
		}},
		style.Rule{Class: "inset-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTop},
			style.Declaration{Property: style.PropRight},
			style.Declaration{Property: style.PropBottom},
			style.Declaration{Property: style.PropLeft},
		}},
		style.Rule{Class: "top-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTop, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "top-full", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTop, Length: style.Length{Unit: style.Percent, Value: 100}},
		}},
		style.Rule{Class: "right-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRight},
		}},
		style.Rule{Class: "left-10", Decls: []style.Declaration{
			style.Declaration{Property: style.PropLeft, Length: style.Length{Value: 10}},
		}},
		style.Rule{Class: "col-span-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridColumnStart, GridLine: style.GridLine{Span: 2}},
			style.Declaration{Property: style.PropGridColumnEnd, GridLine: style.GridLine{Span: 2}},
		}},
		style.Rule{Class: "col-start-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridColumnStart, GridLine: style.GridLine{Line: 2}},
		}},
		style.Rule{Class: "row-span-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridRowStart, GridLine: style.GridLine{Span: 2}},
			style.Declaration{Property: style.PropGridRowEnd, GridLine: style.GridLine{Span: 2}},
		}},
		style.Rule{Class: "row-start-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridRowStart, GridLine: style.GridLine{Line: 1}},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "grid", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayGrid},
		}},
		style.Rule{Class: "aspect-video", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAspectRatio, Number: 1.7777777777777777},
		}},
		style.Rule{Class: "h-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "h-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "h-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "h-fit", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Unit: style.FitContent}},
		}},
		style.Rule{Class: "w-6", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 6}},
		}},
		style.Rule{Class: "w-10", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 10}},
		}},
		style.Rule{Class: "w-20", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 20}},
		}},
		style.Rule{Class: "w-40", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 40}},
		}},
		style.Rule{Class: "w-60", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 60}},
		}},
		style.Rule{Class: "w-fit", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Unit: style.FitContent}},
		}},
		style.Rule{Class: "w-full", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Unit: style.Percent, Value: 100}},
		}},
		style.Rule{Class: "shrink-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShrink},
		}},
		style.Rule{Class: "-translate-x-1/2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTranslateX, Length: style.Length{Unit: style.Percent, Value: -50}},
		}},
		style.Rule{Class: "translate-x-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTranslateX, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "translate-y-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTranslateY, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "animate-pulse", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAnimationKeyframes, Keyframes: style.KeyframesPulse},
			style.Declaration{Property: style.PropAnimationDuration, Duration: 2000000000},
			style.Declaration{Property: style.PropAnimationEasing, Easing: style.Easing{X1: 0.4, X2: 0.6, Y2: 1}},
			style.Declaration{Property: style.PropAnimationIterations, Number: 1, Flag: true},
		}},
		style.Rule{Class: "auto-rows-min", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridAutoRows, Tracks: []style.Track{
				style.Track{Min: style.Breadth{Kind: style.SizeMinContent}, Max: style.Breadth{Kind: style.SizeMinContent}},
			}},
		}},
		style.Rule{Class: "grid-cols-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridColumns, Tracks: []style.Track{
				style.Track{Min: style.Breadth{Kind: style.SizeCells}, Max: style.Breadth{Kind: style.SizeFr, Value: 1}},
				style.Track{Min: style.Breadth{Kind: style.SizeCells}, Max: style.Breadth{Kind: style.SizeFr, Value: 1}},
				style.Track{Min: style.Breadth{Kind: style.SizeCells}, Max: style.Breadth{Kind: style.SizeFr, Value: 1}},
			}},
		}},
		style.Rule{Class: "grid-cols-[1fr_auto]", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridColumns, Tracks: []style.Track{
				style.Track{Max: style.Breadth{Kind: style.SizeFr, Value: 1}},
				style.Track{},
			}},
		}},
		style.Rule{Class: "grid-rows-[auto_auto]", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridRows, Tracks: []style.Track{
				style.Track{},
				style.Track{},
			}},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "flex-col-reverse", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.ColumnReverse},
		}},
		style.Rule{Class: "flex-row-reverse", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.RowReverse},
		}},
		style.Rule{Class: "flex-wrap", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWrap, Wrap: style.Wrap},
		}},
		style.Rule{Class: "flex-wrap-reverse", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWrap, Wrap: style.WrapReverse},
		}},
		style.Rule{Class: "items-center", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAlignItems, Align: style.AlignCenter},
		}},
		style.Rule{Class: "items-start", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAlignItems, Align: style.AlignStart},
		}},
		style.Rule{Class: "justify-center", Decls: []style.Declaration{
			style.Declaration{Property: style.PropJustify, Justify: style.JustifyCenter},
		}},
		style.Rule{Class: "justify-end", Decls: []style.Declaration{
			style.Declaration{Property: style.PropJustify, Justify: style.JustifyEnd},
		}},
		style.Rule{Class: "gap-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "gap-x-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "self-start", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAlignSelf, Align: style.AlignStart},
		}},
		style.Rule{Class: "justify-self-end", Decls: []style.Declaration{
			style.Declaration{Property: style.PropJustifySelf, Align: style.AlignEnd},
		}},
		style.Rule{Class: "truncate", Decls: []style.Declaration{
			style.Declaration{Property: style.PropOverflowX, Overflow: style.OverflowHidden},
			style.Declaration{Property: style.PropOverflowY, Overflow: style.OverflowHidden},
			style.Declaration{Property: style.PropTextOverflow, TextOverflow: style.TextOverflowEllipsis},
			style.Declaration{Property: style.PropWhiteSpace, WhiteSpace: style.WhiteSpaceNowrap},
		}},
		style.Rule{Class: "overflow-hidden", Decls: []style.Declaration{
			style.Declaration{Property: style.PropOverflowX, Overflow: style.OverflowHidden},
			style.Declaration{Property: style.PropOverflowY, Overflow: style.OverflowHidden},
		}},
		style.Rule{Class: "rounded-lg", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusLg},
		}},
		style.Rule{Class: "rounded-md", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusMd},
		}},
		style.Rule{Class: "rounded-xl", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusLg},
		}},
		style.Rule{Class: "border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderTopWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderRightWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderBottomWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderLeftWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "border-zinc-700", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 255}}},
		}},
		style.Rule{Class: "bg-background", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}, Token: theme.Background, Mix: 100},
		}},
		style.Rule{Class: "bg-background", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.Background, Mix: 100},
		}},
		style.Rule{Class: "bg-black/50", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 128}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 128}}},
		}},
		style.Rule{Class: "bg-card", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}, Token: theme.Card, Mix: 100},
		}},
		style.Rule{Class: "bg-card", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}, Token: theme.Card, Mix: 100},
		}},
		style.Rule{Class: "bg-primary", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}, Token: theme.Primary, Mix: 100},
		}},
		style.Rule{Class: "bg-primary", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Primary, Mix: 100},
		}},
		style.Rule{Class: "bg-zinc-100", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-800", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-900", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-950", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}},
		}},
		style.Rule{Class: "p-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "p-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "p-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 3}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 3}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 3}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "px-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "px-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 3}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "px-6", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 6}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 6}},
		}},
		style.Rule{Class: "py-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "font-semibold", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBold, Flag: true},
		}},
		style.Rule{Class: "break-words", Decls: []style.Declaration{
			style.Declaration{Property: style.PropOverflowWrap, OverflowWrap: style.OverflowWrapBreakWord},
		}},
		style.Rule{Class: "wrap-anywhere", Decls: []style.Declaration{
			style.Declaration{Property: style.PropOverflowWrap, OverflowWrap: style.OverflowWrapAnywhere},
		}},
		style.Rule{Class: "break-all", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWordBreak, WordBreak: style.WordBreakAll},
		}},
		style.Rule{Class: "text-clip", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTextOverflow},
		}},
		style.Rule{Class: "text-ellipsis", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTextOverflow, TextOverflow: style.TextOverflowEllipsis},
		}},
		style.Rule{Class: "whitespace-nowrap", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWhiteSpace, WhiteSpace: style.WhiteSpaceNowrap},
		}},
		style.Rule{Class: "text-card-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.CardForeground, Mix: 100},
		}},
		style.Rule{Class: "text-card-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.CardForeground, Mix: 100},
		}},
		style.Rule{Class: "text-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.Foreground, Mix: 100},
		}},
		style.Rule{Class: "text-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.Foreground, Mix: 100},
		}},
		style.Rule{Class: "text-muted-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 255}}, Token: theme.MutedForeground, Mix: 100},
		}},
		style.Rule{Class: "text-muted-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 159, G: 159, B: 169, A: 255}}, Token: theme.MutedForeground, Mix: 100},
		}},
		style.Rule{Class: "text-primary-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.PrimaryForeground, Mix: 100},
		}},
		style.Rule{Class: "text-primary-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}, Token: theme.PrimaryForeground, Mix: 100},
		}},
		style.Rule{Class: "text-zinc-100", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}},
		}},
		style.Rule{Class: "shadow-lg", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShadow, Shadows: []style.Shadow{
				style.Shadow{Y: 10, Blur: 15, Spread: -3, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
				style.Shadow{Y: 4, Blur: 6, Spread: -4, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
			}},
		}},
		style.Rule{Class: "shadow-sm", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShadow, Shadows: []style.Shadow{
				style.Shadow{Y: 1, Blur: 3, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
				style.Shadow{Y: 1, Blur: 2, Spread: -1, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
			}},
		}},
		style.Rule{Class: "transition-colors", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTransitionProperty, Transition: 15},
			style.Declaration{Property: style.PropTransitionEasing, Easing: style.Easing{X1: 0.4, X2: 0.2, Y2: 1}},
			style.Declaration{Property: style.PropTransitionDuration, Duration: 150000000},
		}},
		style.Rule{Class: "duration-200", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTransitionDuration, Duration: 200000000},
		}},
		style.Rule{Class: "ease-linear", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTransitionEasing, Easing: style.Easing{X2: 1, Y2: 1}},
		}},
		style.Rule{Class: "*:px-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
		}, Target: style.Match{Relation: style.RelationChild}},
		style.Rule{Class: "group-data-[state=open]:hidden", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayNone},
		}, Near: style.Match{Relation: style.RelationAncestor, Class: "group", Attrs: []style.Attr{
			style.Attr{Name: "data-state", Value: "open"},
		}}},
		style.Rule{Class: "group-data-[state=open]:bg-zinc-800", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}},
		}, Near: style.Match{Relation: style.RelationAncestor, Class: "group", Attrs: []style.Attr{
			style.Attr{Name: "data-state", Value: "open"},
		}}},
		style.Rule{Class: "group-data-[state=open]/item:hidden", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayNone},
		}, Near: style.Match{Relation: style.RelationAncestor, Class: "group/item", Attrs: []style.Attr{
			style.Attr{Name: "data-state", Value: "open"},
		}}},
		style.Rule{Class: "peer-disabled:hidden", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayNone},
		}, Near: style.Match{Relation: style.RelationPrevious, Class: "peer", States: style.StateDisabled}},
		style.Rule{Class: "hover:border-zinc-400", When: style.Condition{States: style.StateHover}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 159, G: 159, B: 169, A: 255}}},
		}},
		style.Rule{Class: "hover:bg-zinc-600", When: style.Condition{States: style.StateHover}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 82, G: 82, B: 92, A: 255}}},
		}},
		style.Rule{Class: "focus-visible:ring-2", When: style.Condition{States: style.StateFocusVisible}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropRingWidth, Number: 2},
		}},
		style.Rule{Class: "has-data-[slot=card-action]:grid-cols-[1fr_auto]", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGridColumns, Tracks: []style.Track{
				style.Track{Max: style.Breadth{Kind: style.SizeFr, Value: 1}},
				style.Track{},
			}},
		}, Near: style.Match{Relation: style.RelationDescendant, Attrs: []style.Attr{
			style.Attr{Name: "data-slot", Value: "card-action"},
		}}},
		style.Rule{Class: "sm:flex-row", When: style.Condition{MinCols: 80}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "sm:justify-end", When: style.Condition{MinCols: 80}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropJustify, Justify: style.JustifyEnd},
		}},
		style.Rule{Class: "md:flex-row", When: style.Condition{MinCols: 100}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "md:p-2", When: style.Condition{MinCols: 100}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "lg:p-4", When: style.Condition{MinCols: 140}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "[&_svg]:size-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 4}},
		}, Target: style.Match{Relation: style.RelationDescendant, Element: style.ElementSVG}},
		style.Rule{Class: "[&>svg]:size-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 4}},
		}, Target: style.Match{Relation: style.RelationChild, Element: style.ElementSVG}},
		style.Rule{Class: "hover:[&>svg]:hidden", When: style.Condition{States: style.StateHover}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayNone},
		}, Target: style.Match{Relation: style.RelationChild, Element: style.ElementSVG}},
		style.Rule{Class: "md:[&>svg]:hidden", When: style.Condition{MinCols: 100}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayNone},
		}, Target: style.Match{Relation: style.RelationChild, Element: style.ElementSVG}},
	})
}
