// TWIR version=1 hash=f2c2ed7f672de2e652ec58747dcf47702d3e7b69704a7437f24ba27699871d4f tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package sheet

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
	"github.com/twind-dev/twind/twi/theme"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "aspect-video", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAspectRatio, Number: 1.7777777777777777},
		}},
		style.Rule{Class: "h-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "h-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "h-fit", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Unit: style.FitContent}},
		}},
		style.Rule{Class: "w-10", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 10}},
		}},
		style.Rule{Class: "w-20", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 20}},
		}},
		style.Rule{Class: "w-fit", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Unit: style.FitContent}},
		}},
		style.Rule{Class: "w-full", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Unit: style.Percent, Value: 100}},
		}},
		style.Rule{Class: "shrink-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShrink},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "flex-col-reverse", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.ColumnReverse},
		}},
		style.Rule{Class: "flex-row-reverse", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.RowReverse},
		}},
		style.Rule{Class: "flex-wrap", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWrap, Wrap: style.Wrap},
		}},
		style.Rule{Class: "flex-wrap-reverse", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWrap, Wrap: style.WrapReverse},
		}},
		style.Rule{Class: "items-center", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAlignItems, Align: style.AlignCenter},
		}},
		style.Rule{Class: "justify-center", Decls: []style.Declaration{
			style.Declaration{Property: style.PropJustify, Justify: style.JustifyCenter},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "gap-x-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "truncate", Decls: []style.Declaration{
			style.Declaration{Property: style.PropOverflowX, Overflow: style.OverflowHidden},
			style.Declaration{Property: style.PropOverflowY, Overflow: style.OverflowHidden},
			style.Declaration{Property: style.PropTextOverflow, TextOverflow: style.TextOverflowEllipsis},
			style.Declaration{Property: style.PropWhiteSpace, WhiteSpace: style.WhiteSpaceNowrap},
		}},
		style.Rule{Class: "overflow-hidden", Decls: []style.Declaration{
			style.Declaration{Property: style.PropOverflowX, Overflow: style.OverflowHidden},
			style.Declaration{Property: style.PropOverflowY, Overflow: style.OverflowHidden},
		}},
		style.Rule{Class: "border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderTopWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderRightWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderBottomWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderLeftWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "bg-zinc-800", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-950", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}},
		}},
		style.Rule{Class: "p-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "px-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "text-clip", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTextOverflow},
		}},
		style.Rule{Class: "text-ellipsis", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTextOverflow, TextOverflow: style.TextOverflowEllipsis},
		}},
		style.Rule{Class: "whitespace-nowrap", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWhiteSpace, WhiteSpace: style.WhiteSpaceNowrap},
		}},
		style.Rule{Class: "text-zinc-100", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}},
		}},
		style.Rule{Class: "focus-visible:ring-2", When: style.Condition{States: style.StateFocusVisible}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropRingWidth, Number: 2},
		}},
		style.Rule{Class: "sm:flex-row", When: style.Condition{MinCols: 80}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "sm:justify-end", When: style.Condition{MinCols: 80}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropJustify, Justify: style.JustifyEnd},
		}},
		style.Rule{Class: "md:flex-row", When: style.Condition{MinCols: 100}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "md:p-2", When: style.Condition{MinCols: 100}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "lg:p-4", When: style.Condition{MinCols: 140}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 4}},
		}},
	})
}
