// TWIR version=1 hash=ed37f808f69f56745242200aa7af78d6b52dd0947dcc5b1b844f3055c3ed0aee tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package frames

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
	"github.com/twind-dev/twind/twi/theme"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "pointer-events-none", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPointerEvents, Pointer: style.PointerNone},
		}},
		style.Rule{Class: "invisible", Decls: []style.Declaration{
			style.Declaration{Property: style.PropVisibility, Visibility: style.Hidden},
		}},
		style.Rule{Class: "absolute", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionAbsolute},
		}},
		style.Rule{Class: "relative", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionRelative},
		}},
		style.Rule{Class: "top-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTop},
		}},
		style.Rule{Class: "top-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTop, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "top-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTop, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "left-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropLeft},
		}},
		style.Rule{Class: "left-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropLeft, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "left-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropLeft, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "hidden", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayNone},
		}},
		style.Rule{Class: "aspect-video", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAspectRatio, Number: 1.7777777777777777},
		}},
		style.Rule{Class: "h-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "h-5", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 5}},
		}},
		style.Rule{Class: "h-full", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Unit: style.Percent, Value: 100}},
		}},
		style.Rule{Class: "w-6", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 6}},
		}},
		style.Rule{Class: "w-10", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 10}},
		}},
		style.Rule{Class: "w-12", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 12}},
		}},
		style.Rule{Class: "w-16", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 16}},
		}},
		style.Rule{Class: "w-20", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 20}},
		}},
		style.Rule{Class: "w-fit", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Unit: style.FitContent}},
		}},
		style.Rule{Class: "animate-in", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAnimationKeyframes, Keyframes: style.KeyframesEnter},
			style.Declaration{Property: style.PropAnimationDuration, Duration: 150000000, Fallback: true},
			style.Declaration{Property: style.PropAnimationDelay, Fallback: true},
			style.Declaration{Property: style.PropAnimationEasing, Easing: style.Easing{X1: 0.25, Y1: 0.1, X2: 0.25, Y2: 1}, Fallback: true},
			style.Declaration{Property: style.PropAnimationIterations, Number: 1, Fallback: true},
			style.Declaration{Property: style.PropAnimationFill, Fallback: true},
		}},
		style.Rule{Class: "animate-pulse", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAnimationKeyframes, Keyframes: style.KeyframesPulse},
			style.Declaration{Property: style.PropAnimationDuration, Duration: 2000000000},
			style.Declaration{Property: style.PropAnimationDelay},
			style.Declaration{Property: style.PropAnimationEasing, Easing: style.Easing{X1: 0.4, X2: 0.6, Y2: 1}},
			style.Declaration{Property: style.PropAnimationIterations, Number: 1, Flag: true},
			style.Declaration{Property: style.PropAnimationFill},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "flex-row", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "overflow-hidden", Decls: []style.Declaration{
			style.Declaration{Property: style.PropOverflowX, Overflow: style.OverflowHidden},
			style.Declaration{Property: style.PropOverflowY, Overflow: style.OverflowHidden},
		}},
		style.Rule{Class: "border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderTopWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderRightWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderBottomWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderLeftWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "border-zinc-500", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 255}}},
		}},
		style.Rule{Class: "bg-black", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 255}}},
		}},
		style.Rule{Class: "bg-sky-500", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{G: 166, B: 244, A: 255}}},
		}},
		style.Rule{Class: "bg-sky-500/50", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{G: 166, B: 244, A: 128}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{G: 166, B: 244, A: 128}}},
		}},
		style.Rule{Class: "bg-white", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-100", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-700", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 255}}},
		}},
		style.Rule{Class: "text-black", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 255}}},
		}},
		style.Rule{Class: "text-white", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}},
		}},
		style.Rule{Class: "duration-200", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTailwindDuration, Duration: 200000000},
			style.Declaration{Property: style.PropTransitionDuration, Duration: 200000000},
		}},
		style.Rule{Class: "fade-in-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropEnterOpacity},
			style.Declaration{Property: style.PropEnterOpacity},
		}},
	})
}
