// TWIR version=1 hash=82c7ed99fb41cff0e8a8d68ba62e012e2de06b742bf11984dacb356e8c6cea8b tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package responsive

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
	"github.com/twind-dev/twind/twi/theme"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "max-md:p-1", When: style.Condition{BelowCols: 100}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "md:flex-row", When: style.Condition{MinCols: 100}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "md:p-2", When: style.Condition{MinCols: 100}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "lg:p-4", When: style.Condition{MinCols: 140}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 4}},
		}},
	})
}
