// TWIR version=1 hash=d2a76566a72da336ff1e15c59ac94a48ed58b4a1c92b0f4fb42aed15e18b500b tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package hover

import (
	"github.com/pehcastro/twind/twi/color"
	"github.com/pehcastro/twind/twi/style"
	"github.com/pehcastro/twind/twi/theme"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "fixed", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionFixed},
		}},
		style.Rule{Class: "top-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTop},
		}},
		style.Rule{Class: "left-0", Decls: []style.Declaration{
			style.Declaration{Property: style.PropLeft},
		}},
		style.Rule{Class: "z-50", Decls: []style.Declaration{
			style.Declaration{Property: style.PropZIndex, Number: 50},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "h-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "h-full", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Unit: style.Percent, Value: 100}},
		}},
		style.Rule{Class: "w-8", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 8}},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "flex-row", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "gap-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "bg-black", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-700", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 63, G: 63, B: 70, A: 255}}},
		}},
		style.Rule{Class: "bg-zinc-900", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}},
		}},
		style.Rule{Class: "p-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "px-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "text-white", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}},
		}},
		style.Rule{Class: "text-zinc-400", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 159, G: 159, B: 169, A: 255}}},
		}},
		style.Rule{Class: "hover:bg-sky-500", When: style.Condition{States: style.StateHover}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{G: 166, B: 244, A: 255}}},
		}},
		style.Rule{Class: "focus-visible:underline", When: style.Condition{States: style.StateFocusVisible}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropUnderline, Flag: true},
			style.Declaration{Property: style.PropStrikethrough},
		}},
		style.Rule{Class: "active:bg-red-500", When: style.Condition{States: style.StateActive}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 251, G: 44, B: 54, A: 255}}},
		}},
	})
}
