// TWIR version=1 hash=aa67f06d131b73bbc0cbc0027a680dd253d31848df0b4c20fa28a4c6f20d2fb1 tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package main

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
	"github.com/twind-dev/twind/twi/theme"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "px-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "text-red-500", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 251, G: 44, B: 54, A: 255}}},
		}},
	})
}
