package tailwind

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	konst "github.com/twind-dev/twind/internal/konst/style"
)

func Input(sources []string) string {
	var b strings.Builder
	b.WriteString("@import \"tailwindcss\" source(none);\n")
	for _, s := range sources {
		b.WriteString("@source " + strconv.Quote(filepath.ToSlash(s)) + ";\n")
	}
	b.WriteString(konst.PresetTheme)
	return b.String()
}

func Inputs(dir, generated string) ([]string, string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, "", err
	}
	var hashed strings.Builder
	hashed.WriteString(Header("") + konst.PresetTheme)
	var names []string
	for _, e := range entries {
		if e.IsDir() || e.Name() == generated || filepath.Ext(e.Name()) != ".go" {
			continue
		}
		src, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			return nil, "", err
		}
		hashed.WriteString(e.Name() + "\x00" + strings.ReplaceAll(string(src), "\r\n", "\n") + "\x00")
		names = append(names, e.Name())
	}
	sum := sha256.Sum256([]byte(hashed.String()))
	return names, hex.EncodeToString(sum[:]), nil
}

func Header(hash string) string {
	return fmt.Sprintf("// %s version=%d hash=%s tailwind=%s\n// Code generated by twirgen. DO NOT EDIT.\n\n", konst.IRMagic, konst.IRVersion, hash, konst.TailwindVersion)
}

func Stale(dir, generated string) (bool, error) {
	src, err := os.ReadFile(filepath.Join(dir, generated))
	if err != nil {
		return false, err
	}
	_, hash, err := Inputs(dir, generated)
	if err != nil {
		return false, err
	}
	recorded, _, _ := strings.Cut(string(src), "\n")
	current, _, _ := strings.Cut(Header(hash), "\n")
	return strings.TrimSuffix(recorded, "\r") != current, nil
}
