// TWIR version=1 hash=f9aaf1ca0d4c7dfdf34c00bb9c23a7d458eb4cd17b910dba9816df4b6fec3720 tailwind=4.3.3
// Code generated by twirgen. DO NOT EDIT.

package main

import (
	"github.com/twind-dev/twind/twi/color"
	"github.com/twind-dev/twind/twi/style"
	"github.com/twind-dev/twind/twi/theme"
)

func Styles() (style.Sheet, error) {
	return style.NewSheet(1, []style.Rule{
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginTop},
			style.Declaration{Property: style.PropMarginRight},
			style.Declaration{Property: style.PropMarginBottom},
			style.Declaration{Property: style.PropMarginLeft},
			style.Declaration{Property: style.PropPaddingTop},
			style.Declaration{Property: style.PropPaddingRight},
			style.Declaration{Property: style.PropPaddingBottom},
			style.Declaration{Property: style.PropPaddingLeft},
			style.Declaration{Property: style.PropBorderStyle, BorderStyle: style.BorderSingle},
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Current}},
			style.Declaration{Property: style.PropBorderTopWidth},
			style.Declaration{Property: style.PropBorderRightWidth},
			style.Declaration{Property: style.PropBorderBottomWidth},
			style.Declaration{Property: style.PropBorderLeftWidth},
		}},
		style.Rule{Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "absolute", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionAbsolute},
		}},
		style.Rule{Class: "relative", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPosition, Position: style.PositionRelative},
		}},
		style.Rule{Class: "right-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRight, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "bottom-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBottom, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "left-6", Decls: []style.Declaration{
			style.Declaration{Property: style.PropLeft, Length: style.Length{Value: 6}},
		}},
		style.Rule{Class: "z-10", Decls: []style.Declaration{
			style.Declaration{Property: style.PropZIndex, Number: 10},
		}},
		style.Rule{Class: "mr-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginRight, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "ml-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropMarginLeft, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "flex", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDisplay, Display: style.DisplayFlex},
		}},
		style.Rule{Class: "h-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "h-full", Decls: []style.Declaration{
			style.Declaration{Property: style.PropHeight, Length: style.Length{Unit: style.Percent, Value: 100}},
		}},
		style.Rule{Class: "w-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "w-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "w-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "w-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "w-6", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 6}},
		}},
		style.Rule{Class: "w-10", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 10}},
		}},
		style.Rule{Class: "w-36", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 36}},
		}},
		style.Rule{Class: "w-50", Decls: []style.Declaration{
			style.Declaration{Property: style.PropWidth, Length: style.Length{Value: 50}},
		}},
		style.Rule{Class: "flex-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGrow, Number: 1},
			style.Declaration{Property: style.PropShrink, Number: 1},
			style.Declaration{Property: style.PropBasis, Length: style.Length{Unit: style.Percent}},
		}},
		style.Rule{Class: "grow", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGrow, Number: 1},
		}},
		style.Rule{Class: "flex-col", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection, Direction: style.Column},
		}},
		style.Rule{Class: "flex-row", Decls: []style.Declaration{
			style.Declaration{Property: style.PropDirection},
		}},
		style.Rule{Class: "items-center", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAlignItems, Align: style.AlignCenter},
		}},
		style.Rule{Class: "items-end", Decls: []style.Declaration{
			style.Declaration{Property: style.PropAlignItems, Align: style.AlignEnd},
		}},
		style.Rule{Class: "gap-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "gap-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "gap-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 4}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "gap-5", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRowGap, Length: style.Length{Value: 5}},
			style.Declaration{Property: style.PropColumnGap, Length: style.Length{Value: 5}},
		}},
		style.Rule{Class: "rounded-full", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusFull},
		}},
		style.Rule{Class: "rounded-lg", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusLg},
		}},
		style.Rule{Class: "rounded-md", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusMd},
		}},
		style.Rule{Class: "rounded-sm", Decls: []style.Declaration{
			style.Declaration{Property: style.PropRadius, Radius: style.RadiusSm},
		}},
		style.Rule{Class: "border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBorderTopWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderRightWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderBottomWidth, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropBorderLeftWidth, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "bg-background", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}, Token: theme.Background, Mix: 100},
		}},
		style.Rule{Class: "bg-background", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.Background, Mix: 100},
		}},
		style.Rule{Class: "bg-border", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 228, G: 228, B: 231, A: 255}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "bg-border", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 26}}, Token: theme.Border, Mix: 100},
		}},
		style.Rule{Class: "bg-card", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}, Token: theme.Card, Mix: 100},
		}},
		style.Rule{Class: "bg-card", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}, Token: theme.Card, Mix: 100},
		}},
		style.Rule{Class: "bg-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.Foreground, Mix: 100},
		}},
		style.Rule{Class: "bg-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.Foreground, Mix: 100},
		}},
		style.Rule{Class: "bg-green-500/15", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{G: 201, B: 80, A: 38}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{G: 201, B: 80, A: 38}}},
		}},
		style.Rule{Class: "bg-indigo-500/10", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 97, G: 95, B: 255, A: 26}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 97, G: 95, B: 255, A: 26}}},
		}},
		style.Rule{Class: "bg-indigo-600", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 79, G: 57, B: 246, A: 255}}},
		}},
		style.Rule{Class: "bg-muted", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 244, G: 244, B: 245, A: 255}}, Token: theme.Muted, Mix: 100},
		}},
		style.Rule{Class: "bg-muted", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 39, G: 39, B: 42, A: 255}}, Token: theme.Muted, Mix: 100},
		}},
		style.Rule{Class: "bg-popover", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}, Token: theme.Popover, Mix: 100},
		}},
		style.Rule{Class: "bg-popover", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 24, G: 24, B: 27, A: 255}}, Token: theme.Popover, Mix: 100},
		}},
		style.Rule{Class: "bg-red-500/15", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 251, G: 44, B: 54, A: 38}}},
			style.Declaration{Property: style.PropBackground, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 251, G: 44, B: 54, A: 38}}},
		}},
		style.Rule{Class: "bg-linear-to-r", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGradient, Line: style.GradientLine{Kind: style.GradientLinear, Direction: style.ToRight}},
		}},
		style.Rule{Class: "from-indigo-500", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGradientFrom, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 97, G: 95, B: 255, A: 255}}},
		}},
		style.Rule{Class: "via-fuchsia-500", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGradientVia, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 225, G: 42, B: 251, A: 255}}},
		}},
		style.Rule{Class: "to-pink-600", Decls: []style.Declaration{
			style.Declaration{Property: style.PropGradientTo, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 230, B: 118, A: 255}}},
		}},
		style.Rule{Class: "px-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 1}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "px-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "px-3", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 3}},
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 3}},
		}},
		style.Rule{Class: "pt-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "pt-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingTop, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "pr-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "pr-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingRight, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "pb-1", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingBottom, Length: style.Length{Value: 1}},
		}},
		style.Rule{Class: "pl-2", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 2}},
		}},
		style.Rule{Class: "pl-4", Decls: []style.Declaration{
			style.Declaration{Property: style.PropPaddingLeft, Length: style.Length{Value: 4}},
		}},
		style.Rule{Class: "text-right", Decls: []style.Declaration{
			style.Declaration{Property: style.PropTextAlign, TextAlign: style.TextRight},
		}},
		style.Rule{Class: "font-bold", Decls: []style.Declaration{
			style.Declaration{Property: style.PropBold, Flag: true},
		}},
		style.Rule{Class: "text-card-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.CardForeground, Mix: 100},
		}},
		style.Rule{Class: "text-card-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.CardForeground, Mix: 100},
		}},
		style.Rule{Class: "text-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.Foreground, Mix: 100},
		}},
		style.Rule{Class: "text-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.Foreground, Mix: 100},
		}},
		style.Rule{Class: "text-green-600", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{G: 166, B: 62, A: 255}}},
		}},
		style.Rule{Class: "text-indigo-500", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 97, G: 95, B: 255, A: 255}}},
		}},
		style.Rule{Class: "text-indigo-600", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 79, G: 57, B: 246, A: 255}}},
		}},
		style.Rule{Class: "text-muted-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 113, G: 113, B: 123, A: 255}}, Token: theme.MutedForeground, Mix: 100},
		}},
		style.Rule{Class: "text-muted-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 159, G: 159, B: 169, A: 255}}, Token: theme.MutedForeground, Mix: 100},
		}},
		style.Rule{Class: "text-popover-foreground", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 9, G: 9, B: 11, A: 255}}, Token: theme.PopoverForeground, Mix: 100},
		}},
		style.Rule{Class: "text-popover-foreground", When: style.Condition{Scheme: style.SchemeDark}, Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 250, G: 250, B: 250, A: 255}}, Token: theme.PopoverForeground, Mix: 100},
		}},
		style.Rule{Class: "text-white", Decls: []style.Declaration{
			style.Declaration{Property: style.PropColor, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{R: 255, G: 255, B: 255, A: 255}}},
		}},
		style.Rule{Class: "shadow-lg", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShadow, Shadows: []style.Shadow{
				style.Shadow{Y: 10, Blur: 15, Spread: -3, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
				style.Shadow{Y: 4, Blur: 6, Spread: -4, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
			}},
		}},
		style.Rule{Class: "shadow-md", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShadow, Shadows: []style.Shadow{
				style.Shadow{Y: 4, Blur: 6, Spread: -1, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
				style.Shadow{Y: 2, Blur: 4, Spread: -2, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
			}},
		}},
		style.Rule{Class: "shadow-sm", Decls: []style.Declaration{
			style.Declaration{Property: style.PropShadow, Shadows: []style.Shadow{
				style.Shadow{Y: 1, Blur: 3, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
				style.Shadow{Y: 1, Blur: 2, Spread: -1, Color: color.Color{Kind: color.Literal, RGBA: color.RGBA{A: 26}}, Tintable: true},
			}},
		}},
	})
}
